db:
    image: postgres:9.6.1-alpine
    environment:
        - PGDATA=/var/lib/postgresql/data/pgdata
        - POSTGRES_PASSWORD=CliNiCk00H!df
        - POSTGRES_DB=clinic
    privileged: true
    ports:
        - 5432:5432
    volumes:
        - ./.volumes/db/data/:/var/lib/postgresql/data/pgdata/
app:
    build: ./src/
    volumes:
        - ./src/:/usr/src/app/
    environment:
        - IN_DOCKER=true
    links:
        - db
    ports:
        - 80:80
